apiVersion: sandbox.demo/v1
kind: Sandbox
metadata:
  name: sbx-manifest2
spec:
  egress: true
  ports:
    - hostPort: 30081
      containerPort: 8080
      protocol: tcp
  containers:
    - name: web
      image: python:3.12-alpine
      args:
        - sh
        - -c
        - |
          mkdir -p /tmp/www &&
          echo "sandbox-demo-web2" > /tmp/www/index.html &&
          cd /tmp/www &&
          python -m http.server 8080
      env: []
      limits:
        memoryBytes: 134217728
        cpuQuota: 50000
        cpuPeriod: 100000
        pidsLimit: 128

    - name: worker
      image: alpine:3.20
      args:
        - sh
        - -c
        - |
          while true; do
            echo "sandbox-demo-worker2 alive";
            sleep 60;
          done
      env: []
      limits:
        memoryBytes: 134217728
        cpuQuota: 50000
        cpuPeriod: 100000
        pidsLimit: 128
